services:
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: rainy_api
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Database=RainyScore;Username=postgres;Password=1234
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16
    container_name: rainy_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: RainyScore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d RainyScore"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
