// <auto-generated />
using System;
using System.Text.Json;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ScoreDbContext))]
    [Migration("20260605075449_teams_country_id_added")]
    partial class teams_country_id_added
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortCode")
                        .HasColumnType("text")
                        .HasColumnName("short_code");

                    b.HasKey("Id")
                        .HasName("pk_countries");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_name");

                    b.HasIndex("ShortCode")
                        .IsUnique()
                        .HasDatabaseName("ix_countries_short_code");

                    b.ToTable("countries", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "England",
                            ShortCode = "ENG"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Scotland",
                            ShortCode = "SCT"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Germany",
                            ShortCode = "GER"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Italy",
                            ShortCode = "ITA"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Spain",
                            ShortCode = "ESP"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "France",
                            ShortCode = "FRA"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Netherlands",
                            ShortCode = "NL"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Belgium",
                            ShortCode = "BEL"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Portugal",
                            ShortCode = "PRT"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Turkey",
                            ShortCode = "TUR"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Greece",
                            ShortCode = "GRC"
                        });
                });

            modelBuilder.Entity("Domain.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCup")
                        .HasColumnType("boolean")
                        .HasColumnName("is_cup");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortCode")
                        .HasColumnType("text")
                        .HasColumnName("short_code");

                    b.HasKey("Id")
                        .HasName("pk_leagues");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_leagues_country_id");

                    b.ToTable("leagues", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Premier League",
                            ShortCode = "E0"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Championship",
                            ShortCode = "E1"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "League One",
                            ShortCode = "E2"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "League Two",
                            ShortCode = "E3"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "National League",
                            ShortCode = "EC"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Premiership",
                            ShortCode = "SC0"
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Championship",
                            ShortCode = "SC1"
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "League One",
                            ShortCode = "SC2"
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 2,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "League Two",
                            ShortCode = "SC3"
                        },
                        new
                        {
                            Id = 10,
                            CountryId = 3,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Bundesliga",
                            ShortCode = "D1"
                        },
                        new
                        {
                            Id = 11,
                            CountryId = 3,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "2. Bundesliga",
                            ShortCode = "D2"
                        },
                        new
                        {
                            Id = 12,
                            CountryId = 4,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Serie A",
                            ShortCode = "I1"
                        },
                        new
                        {
                            Id = 13,
                            CountryId = 4,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Serie B",
                            ShortCode = "I2"
                        },
                        new
                        {
                            Id = 14,
                            CountryId = 5,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "La Liga",
                            ShortCode = "SP1"
                        },
                        new
                        {
                            Id = 15,
                            CountryId = 5,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Segunda División",
                            ShortCode = "SP2"
                        },
                        new
                        {
                            Id = 16,
                            CountryId = 6,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Ligue 1",
                            ShortCode = "F1"
                        },
                        new
                        {
                            Id = 17,
                            CountryId = 6,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Ligue 2",
                            ShortCode = "F2"
                        },
                        new
                        {
                            Id = 18,
                            CountryId = 7,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Eredivisie",
                            ShortCode = "N1"
                        },
                        new
                        {
                            Id = 19,
                            CountryId = 8,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Jupiler Pro League",
                            ShortCode = "B1"
                        },
                        new
                        {
                            Id = 20,
                            CountryId = 9,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Primeira Liga",
                            ShortCode = "P1"
                        },
                        new
                        {
                            Id = 21,
                            CountryId = 10,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Süper Lig",
                            ShortCode = "T1"
                        },
                        new
                        {
                            Id = 22,
                            CountryId = 11,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCup = false,
                            Name = "Super League 1",
                            ShortCode = "G1"
                        });
                });

            modelBuilder.Entity("Domain.Entities.LeagueExternalMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<int>("ExternalLeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("external_league_id");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.HasKey("Id")
                        .HasName("pk_league_external_maps");

                    b.HasIndex("ExternalLeagueId", "DataSource")
                        .IsUnique()
                        .HasDatabaseName("ix_league_external_maps_external_league_id_data_source");

                    b.HasIndex("LeagueId", "DataSource")
                        .IsUnique()
                        .HasDatabaseName("ix_league_external_maps_league_id_data_source");

                    b.ToTable("league_external_maps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 39,
                            LeagueId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 40,
                            LeagueId = 2
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 41,
                            LeagueId = 3
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 42,
                            LeagueId = 4
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 43,
                            LeagueId = 5
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 179,
                            LeagueId = 6
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 180,
                            LeagueId = 7
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 183,
                            LeagueId = 8
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 184,
                            LeagueId = 9
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 78,
                            LeagueId = 10
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 79,
                            LeagueId = 11
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 135,
                            LeagueId = 12
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 136,
                            LeagueId = 13
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 140,
                            LeagueId = 14
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 141,
                            LeagueId = 15
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 61,
                            LeagueId = 16
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 62,
                            LeagueId = 17
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 88,
                            LeagueId = 18
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 144,
                            LeagueId = 19
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 94,
                            LeagueId = 20
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 203,
                            LeagueId = 21
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 10, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            DataSource = "apifootball",
                            ExternalLeagueId = 197,
                            LeagueId = 22
                        });
                });

            modelBuilder.Entity("Domain.Entities.MatchDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("away_team_id");

                    b.Property<decimal?>("AwayWinOdds")
                        .HasColumnType("numeric")
                        .HasColumnName("away_win_odds");

                    b.Property<int?>("BookmakerId")
                        .HasColumnType("integer")
                        .HasColumnName("bookmaker_id");

                    b.Property<string>("BookmakerName")
                        .HasColumnType("text")
                        .HasColumnName("bookmaker_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DataSource")
                        .HasColumnType("text")
                        .HasColumnName("data_source");

                    b.Property<decimal?>("DrawWinOdds")
                        .HasColumnType("numeric")
                        .HasColumnName("draw_win_odds");

                    b.Property<int?>("FixtureId")
                        .HasColumnType("integer")
                        .HasColumnName("fixture_id");

                    b.Property<int?>("FullTimeAwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("full_time_away_goals");

                    b.Property<int?>("FullTimeHomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("full_time_home_goals");

                    b.Property<char?>("FullTimeWiner")
                        .HasColumnType("character(1)")
                        .HasColumnName("full_time_winer");

                    b.Property<decimal?>("GoalsOver25Odds")
                        .HasColumnType("numeric")
                        .HasColumnName("goals_over_2_5_odds");

                    b.Property<decimal?>("GoalsUnder25Odds")
                        .HasColumnType("numeric")
                        .HasColumnName("goals_under_2_5_odds");

                    b.Property<int?>("HalfTimeAwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("half_time_away_goals");

                    b.Property<int?>("HalfTimeHomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("half_time_home_goals");

                    b.Property<char?>("HalfTimeWiner")
                        .HasColumnType("character(1)")
                        .HasColumnName("half_time_winer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_id");

                    b.Property<decimal?>("HomeWinOdds")
                        .HasColumnType("numeric")
                        .HasColumnName("home_win_odds");

                    b.Property<bool>("IsHistory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_history");

                    b.Property<int>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.Property<DateOnly>("MatchDate")
                        .HasColumnType("date")
                        .HasColumnName("match_date");

                    b.Property<TimeOnly>("MatchTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("match_time");

                    b.Property<JsonDocument>("OriginalResponseOdds")
                        .HasColumnType("jsonb")
                        .HasColumnName("original_response_odds");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_match_details");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_match_details_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_match_details_home_team_id");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_match_details_league_id");

                    b.HasIndex("DataSource", "FixtureId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_details_data_source_fixture_id");

                    b.ToTable("match_details", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Stadium", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("TerrainType")
                        .HasColumnType("text")
                        .HasColumnName("terrain_type");

                    b.HasKey("Id")
                        .HasName("pk_stadiums");

                    b.ToTable("stadiums", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("integer")
                        .HasColumnName("country_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ShortCode")
                        .HasColumnType("text")
                        .HasColumnName("short_code");

                    b.Property<int?>("StadiumId")
                        .HasColumnType("integer")
                        .HasColumnName("stadium_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("CountryId")
                        .HasDatabaseName("ix_teams_country_id");

                    b.HasIndex("StadiumId")
                        .HasDatabaseName("ix_teams_stadium_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WeatherCondition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CloudCover")
                        .HasColumnType("integer")
                        .HasColumnName("cloud_cover");

                    b.Property<int>("CloudCoverLow")
                        .HasColumnType("integer")
                        .HasColumnName("cloud_cover_low");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DewPoint2m")
                        .HasColumnType("numeric")
                        .HasColumnName("dew_point_2m");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric")
                        .HasColumnName("longitude");

                    b.Property<int>("MatchDetailsId")
                        .HasColumnType("integer")
                        .HasColumnName("match_details_id");

                    b.Property<string>("OriginalResponse")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_response");

                    b.Property<decimal>("Precipitation")
                        .HasColumnType("numeric")
                        .HasColumnName("precipitation");

                    b.Property<decimal>("SunshineDuration")
                        .HasColumnType("numeric")
                        .HasColumnName("sunshine_duration");

                    b.Property<decimal>("Temperature2m")
                        .HasColumnType("numeric")
                        .HasColumnName("temperature_2m");

                    b.Property<int>("WeatherCode")
                        .HasColumnType("integer")
                        .HasColumnName("weather_code");

                    b.Property<string>("WeatherServiceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("weather_service_code");

                    b.Property<decimal>("WindSpeed10m")
                        .HasColumnType("numeric")
                        .HasColumnName("wind_speed_10m");

                    b.HasKey("Id")
                        .HasName("pk_weather_conditions");

                    b.HasIndex("MatchDetailsId")
                        .IsUnique()
                        .HasDatabaseName("ix_weather_conditions_match_details_id");

                    b.ToTable("weather_conditions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.League", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("Leagues")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_leagues_countries_country_id");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.LeagueExternalMap", b =>
                {
                    b.HasOne("Domain.Entities.League", "League")
                        .WithMany("LeagueExternalMaps")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_league_external_maps_leagues_league_id");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Domain.Entities.MatchDetails", b =>
                {
                    b.HasOne("Domain.Entities.Team", "AwayTeam")
                        .WithMany("AwayMatches")
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_details_teams_away_team_id");

                    b.HasOne("Domain.Entities.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_details_teams_home_team_id");

                    b.HasOne("Domain.Entities.League", "League")
                        .WithMany("MatchDetails")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_details_leagues_league_id");

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("Teams")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teams_countries_country_id");

                    b.HasOne("Domain.Entities.Stadium", "Stadium")
                        .WithMany("Teams")
                        .HasForeignKey("StadiumId")
                        .HasConstraintName("fk_teams_stadiums_stadium_id");

                    b.Navigation("Country");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("Domain.Entities.WeatherCondition", b =>
                {
                    b.HasOne("Domain.Entities.MatchDetails", "MatchDetails")
                        .WithOne("WeatherCondition")
                        .HasForeignKey("Domain.Entities.WeatherCondition", "MatchDetailsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_weather_conditions_match_details_match_details_id");

                    b.Navigation("MatchDetails");
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Navigation("Leagues");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.League", b =>
                {
                    b.Navigation("LeagueExternalMaps");

                    b.Navigation("MatchDetails");
                });

            modelBuilder.Entity("Domain.Entities.MatchDetails", b =>
                {
                    b.Navigation("WeatherCondition");
                });

            modelBuilder.Entity("Domain.Entities.Stadium", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Team", b =>
                {
                    b.Navigation("AwayMatches");

                    b.Navigation("HomeMatches");
                });
#pragma warning restore 612, 618
        }
    }
}
